version: 2.1
jobs:
  build:
    docker:
      - image: nixpkgs:nix
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - pie-v1-{{ checksum "nix/sources.json" }}
      - run:
          name: Build
          command: nix build -v -f release.nix
      - save_cache:
          name: Cached Dependencies
          key: pie-v1-{{ checksum "nix/sources.json" }}
          paths:
            - "/nix"
