version: 2.1
jobs:
  build:
    docker:
      - image: nixos:nix
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - pie-v1-{{ checksum "pie.cabal" }}
      - run:
          name: Build
          command: nix build -v -f release.nix
      - save_cache:
          name: Cached Dependencies
          key: pie-v1-{{ checksum "pie.cabal" }}
          paths:
            - "/nix"
